export {default as Home} from './Home'
export {default as Developers} from './Developers'
export {default as Developer} from './Developer'
export {default as LunchDetails} from './LunchDetails'
export {default as CompoundDetails} from './CompoundDetails'